fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    java7: "git://github.com/softek/puppet-java7.git"
    wget: "git://github.com/maestrodev/puppet-wget.git"
  symlinks:
    crowd: "#{source_dir}"
