name          'antonlindstrom-crowd'
version       '0.0.1'
source        'UNKNOWN'
author        'antonlindstrom'
license       'MIT'
summary       'UNKNOWN'
description   'UNKNOWN'
project_page  'UNKNOWN'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'maestrodev/wget', '>= 1.2.2'
dependency 'softek/java7', '>= 0.1.0'
